# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2aea487d59b3908d05fd389699b4ec7f4b68b559bd49200b09d640178377ccc819896f80e2f6e2b728d41f0f0bbdcb9c53664a184e7bcb5d4361e862b5f7b77e

test:
  secret_key_base: 1d7d62df885871bdd47aac77a5ebe64b1b067a2000de719f522b889a16ebb6f060efb0ac17bd70263858519fc5892a137ebfa7ab4e0029dd5f55f40dec17b63e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
